### ISSUE TITLE
failed to boot on learn-uxn

### ISSUE THREAD

**Issue by metasyn** [marzhall/dvd_screen#1]
hey @marzhall !

i recently had to update learn-uxn to the recent refactoring happening the main uxn repo. i think some of the changes caused your dvd rom to no longer boot. due to that, i removed the link to the rom. if you are able to get it working again, please let me know, and i'll add a link to it again in the roms list :)

best,
xander

**Comment by marzhall** [comment]
Hi Xander! It seems to run if I copy-paste the source into `https://metasyn.github.io/learn-uxn/#` and hit assemble - or has the site not updated yet?

**Comment by metasyn** [comment]
Oh, silly me. I just needed to update the dvd.tal. Fixed!

**Comment by marzhall** [comment]
Good to hear!
